[package]
name = "pointz"
version = "0.1.1"
authors = ["Anton Zelenin <ntnzelenin@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {path = '../../other_repos/iced', default_features = false, features = ["wgpu"] }
iced_winit = {path = '../../other_repos/iced/winit'}
iced_wgpu = {path = '../../other_repos/iced/wgpu'}
wgpu = "0.9"
cgmath = "0.18"
bytemuck = "1.7.2"
shaderc = "0.7.3"
image = "0.23.14"
log = "0.4.14"
tobj = "2.0.3"
anyhow = "1.0.44"
glam = "0.20.0"
ordered-float = "2.8"
