[package]
name = "pointz"
version = "0.1.0"
authors = ["Anton Zelenin <ntnzelenin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {path = '/home/anton/Documents/other_repos/iced'}
iced_winit = {path = '/home/anton/Documents/other_repos/iced/winit'}
iced_wgpu = {path = '/home/anton/Documents/other_repos/iced/wgpu'}
winit = "0.22"
cgmath = "0.17.0"
bytemuck = "1.3.1"
shaderc = "0.6.2"
