[package]
name = "pointz"
version = "0.2.0"
authors = ["Anton Zelenin <ntnzelenin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {path = '../../other_repos/iced'}
iced_winit = {path = '../../other_repos/iced/winit'}
iced_wgpu = {path = '../../other_repos/iced/wgpu'}
cgmath = "0.17"
bytemuck = "1.4.1"
shaderc = "0.7"
image = "0.23"
log = "0.4.11"
env_logger = "0.7.1"
tobj = "2.0.2"
anyhow = "1.0"
