[package]
name = "pointz"
version = "0.1.0"
authors = ["Anton Zelenin <ntnzelenin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {path = '../../other_repos/iced'}
iced_winit = {path = '../../other_repos/iced/winit'}
iced_wgpu = {path = '../../other_repos/iced/wgpu'}
winit = "0.22"
cgmath = "0.17"
bytemuck = "1.3"
shaderc = "0.6"
image = "0.23"
failure = "0.1"
log = "0.4.11"
env_logger = "0.7.1"
