[package]
name = "pointz"
version = "0.2.0"
authors = ["Anton Zelenin <ntnzelenin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {path = '../../other_repos/iced'}
iced_winit = {path = '../../other_repos/iced/winit'}
iced_wgpu = {path = '../../other_repos/iced/wgpu'}
cgmath = "0.18"
bytemuck = "1.5.0"
shaderc = "0.7.1"
image = "0.23.13"
log = "0.4.14"
env_logger = "0.8.3"
tobj = "2.0.3"
anyhow = "1.0.38"
legion = "0.3.1"
